repos:
  - repo: local
    hooks:
      - id: make-format
        name: Run "make format"
        entry: make format
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: make-check
        name: Run "make check"
        entry: make check
        language: system
        pass_filenames: false
        stages: [pre-push]